package tbs;
//TBS Version 0.3

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.TreeMap;

import javax.imageio.ImageIO;
import javax.swing.JApplet;

import tbs.controller.TBSController;
import tbs.model.TBSButton;
import tbs.model.TBSModel;
import tbs.view.TBSView;

public class TBSGraphics {
	
	/**
	 * 8-byte serialization class ID generated by
	 * https://www.fourmilab.ch/hotbits/secure_generate.html
	 */
	private static final long serialVersionUID = 0xE6D7FA0516CC8DB2L;
	
	public static int buttonHeight;
	public static int buttonWidth;
	public static TBSButton linkButton, unlinkButton, labelButton, deleteButton, splitButton, printButton, undoButton,
			saveButton;	
	
	//boundary between active and inactive elements.
	//Name can be changed. 
	public static int LINE_OF_DEATH = 120;
	
	// Contains the length and width of all organism nodes
	public static int organismNodeWidth = 0;
	public static int organismNodeHeight = 0;
	
	// minimum number of pixels around the right and left of an organism's name
	public static int paddingWidth = 5;
	
	// Space between bottom and top of images
	public static int ySpacing = 1;
	
	// Font Properties
	public static String fontName = "default"; // Use default font
	public static int fontStyle = Font.BOLD;
	public static int fontSize = 16;
	
}
