package admin;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

import java.awt.event.ActionEvent;

public class ActionHandler extends JPanel {    
	/**
	 * 8-byte serialization class ID generated by
	 * https://www.fourmilab.ch/hotbits/secure_generate.html
	 */
	private static final long serialVersionUID = 0x60655B840361BFA4L;
	
	public Action exitAction;
	public Action printAction;
	public Action nextAction;
	public Action hullAction;
	public AdminApplication parent;
	
	
	public class ExitAction extends AbstractAction {

		private static final long serialVersionUID = 1740545338294704279L;

		public ExitAction() {
			super("Exit");
		}

		//@0verride
		public void actionPerformed(ActionEvent arg0) {
			System.exit(0);
		}
	}
	
	public class PrintAction extends AbstractAction {

		private static final long serialVersionUID = 1740545322294704279L;

		public PrintAction() {
			super("Print To Console");
		}

		//@0verride
		public void actionPerformed(ActionEvent arg0) {
			parent.printGraphInfo();
		}
	}
	
	public class HullAction extends AbstractAction {

		private static final long serialVersionUID = 1740545322294704279L;

		public HullAction() {
			super("Hull Collision");
		}

		//@0verride
		public void actionPerformed(ActionEvent arg0) {
			parent.checkHullCollisions();
		}
	}
	
	public class NextAction extends AbstractAction {

		private static final long serialVersionUID = 1740545444294704279L;

		public NextAction() {
			super("Next Graph");
		}

		//@0verride
		public void actionPerformed(ActionEvent arg0) {
			parent.nextGraph();
		}
	}
	
    public ActionHandler() {
        exitAction = new ExitAction();
        hullAction = new HullAction();
        printAction = new PrintAction();
        nextAction = new NextAction();
    }
    
    public void setParent(AdminApplication parent) {
    	this.parent = parent;
    }
    
    public JMenuBar createMenuBar() {
        JMenuBar menuBar;
        JMenu fileMenu;
        JMenuItem printItem;
        JMenuItem hullItem;
        JMenuItem nextItem;
        JMenuItem exitItem;
        
        //Create the menu bar.
        menuBar = new JMenuBar();
        fileMenu = new JMenu("File");
        menuBar.add(fileMenu);

        //a group of JMenuItems
        printItem = new JMenuItem(printAction);
        hullItem = new JMenuItem(hullAction);
        nextItem = new JMenuItem(nextAction);
        exitItem = new JMenuItem(exitAction);
        fileMenu.add(printItem);
        fileMenu.add(hullItem);
        fileMenu.add(nextItem);
        fileMenu.add(exitItem);
        

       return menuBar;
    }
}
